version: '2.2'
services:
  zookeeper:
    build: zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: kafka
    scale: 3
    ports:
      - "9092"
    environment:
      BROKER_ID_COMMAND: "docker ps | grep $$HOSTNAME | grep -o '[0-9]$$'"
      KAFKA_ADVERTISED_HOST_NAME: 10.0.23.42
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_PROTOCOL_VERSION: 0.8.2.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  # kafka-override:
  #   build: kafka
  #   ports:
  #     - "9092"
  #   environment:
  #     KAFKA_BROKER_ID: 2
  #     KAFKA_ADVERTISED_HOST_NAME: 10.0.23.42
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_INTER_BROKER_PROTOCOL_VERSION: 0.8.2.2
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
